/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pacote;

import java.math.BigInteger;
import Pacote.RSA;
import java.awt.Color;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import javax.swing.text.AbstractDocument;
/**
 *
 * @author andre
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        
        initComponents();
        setLocationRelativeTo(null);
        txtMensagemCripto.setBackground(new Color(0,0,0,0));
        txtMensagemDescripto.setBackground(new Color(0,0,0,0));
        txtMensagem.setBackground(new Color(0,0,0,0));
        txtMensagemCripto.setLineWrap(true);
        txtMensagemDescripto.setLineWrap(true);
        txtMensagem.setLineWrap(true);
        btnCriptografar.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMensagem = new javax.swing.JTextArea();
        txtMensagemCripto = new javax.swing.JTextArea();
        txtMensagemDescripto = new javax.swing.JTextArea();
        btnCriptografar = new javax.swing.JButton();
        lblMensagemInt = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        lblPhi_n = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblQ = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMensagem.setColumns(20);
        txtMensagem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMensagem.setForeground(new java.awt.Color(255, 255, 255));
        txtMensagem.setRows(5);
        txtMensagem.setBorder(null);
        getContentPane().add(txtMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 360, 180));

        txtMensagemCripto.setEditable(false);
        txtMensagemCripto.setColumns(20);
        txtMensagemCripto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMensagemCripto.setForeground(new java.awt.Color(255, 255, 255));
        txtMensagemCripto.setRows(5);
        txtMensagemCripto.setBorder(null);
        getContentPane().add(txtMensagemCripto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 360, 180));

        txtMensagemDescripto.setEditable(false);
        txtMensagemDescripto.setColumns(20);
        txtMensagemDescripto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMensagemDescripto.setForeground(new java.awt.Color(255, 255, 255));
        txtMensagemDescripto.setRows(5);
        txtMensagemDescripto.setBorder(null);
        getContentPane().add(txtMensagemDescripto, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 360, 180));

        btnCriptografar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCriptografar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriptografarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriptografar, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 645, 310, 50));

        lblMensagemInt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMensagemInt.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagemInt.setText("MensagemInt =");
        getContentPane().add(lblMensagemInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        lblMsg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblMsg.setText("Mensagem criptografada = (MensagemInt ᵉ )mod n");
        getContentPane().add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        lblD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblD.setForeground(new java.awt.Color(255, 255, 255));
        lblD.setText("d ≡ e-¹ mod ϕ(n) =");
        getContentPane().add(lblD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        lblE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblE.setForeground(new java.awt.Color(255, 255, 255));
        lblE.setText("e =");
        getContentPane().add(lblE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        lblPhi_n.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPhi_n.setForeground(new java.awt.Color(255, 255, 255));
        lblPhi_n.setText("φ(n) = (p-1)x(q-1) = ");
        getContentPane().add(lblPhi_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        lblN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblN.setForeground(new java.awt.Color(255, 255, 255));
        lblN.setText("n = p x q =");
        getContentPane().add(lblN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        lblQ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQ.setForeground(new java.awt.Color(255, 255, 255));
        lblQ.setText("q =");
        getContentPane().add(lblQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        lblP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblP.setForeground(new java.awt.Color(255, 255, 255));
        lblP.setText("p =");
        getContentPane().add(lblP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Group 18.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriptografarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriptografarActionPerformed
        RSA rsa = new RSA();
        String msg = txtMensagem.getText();
         try {
            
            byte[] byteArray = msg.getBytes(StandardCharsets.UTF_8);
            int sizeInBytes = byteArray.length;

        // Converter bytes para bits
            int sizeInBits = sizeInBytes * 16; 
            int tamanhoChave = sizeInBits;  // Define o tamanho da chave em bits

            // Gerar par de chaves (pública e privada)
            BigInteger[] chaves = rsa.gerarParDeChaves(tamanhoChave, lblP, lblQ, lblN, lblPhi_n, lblE,lblD);
            BigInteger e = chaves[0];  // Expoente público
            BigInteger d = chaves[1];  // Expoente privado
            BigInteger n = chaves[2];  // Módulo

            // Exibir as variáveis
            System.out.println("Chave Pública (e, n): " + e + ", " + n);
            System.out.println("Chave Privada (d, n): " + d + ", " + n);

            // O cliente quer enviar uma mensagem para o servidor
            String mensagem = msg;
            System.out.println("Mensagem Original: " + mensagem);

            // Criptografar a mensagem usando a chave pública
            BigInteger mensagemCriptografada = rsa.criptografar(e, n, mensagem,lblMensagemInt);
            System.out.println("Mensagem Criptografada (número inteiro): " + mensagemCriptografada);

            // Descriptografar a mensagem usando a chave privada
            String mensagemDescriptografada = rsa.descriptografar(d, n, mensagemCriptografada);
            System.out.println("Mensagem Descriptografada: " + mensagemDescriptografada);
            
            txtMensagemCripto.setText(String.valueOf(mensagemCriptografada));
            txtMensagemDescripto.setText(mensagemDescriptografada);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCriptografarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriptografar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblMensagemInt;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblPhi_n;
    private javax.swing.JLabel lblQ;
    private javax.swing.JTextArea txtMensagem;
    private javax.swing.JTextArea txtMensagemCripto;
    private javax.swing.JTextArea txtMensagemDescripto;
    // End of variables declaration//GEN-END:variables
}
