/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pacote;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaSaida extends javax.swing.JFrame {
    String tipo = "Saída";
    int id;
    public TelaSaida() {
        initComponents();
        setLocationRelativeTo(null);
        btnCadSaida.setBackground(new Color(0,0,0,0));
        txtData.setBackground(new Color(0,0,0,0));
        txtValor.setBackground(new Color(0,0,0,0));
        cbxCategoria.setBackground(new Color(0,0,0,0));
        cbxFixaVariavel.setBackground(new Color(0,0,0,0));
        cbxAtivoPassivo.setBackground(new Color(0,0,0,0));
        btnConfirmarEdit.setBackground(new Color(0,0,0,0));
        btnEditSaida.setBackground(new Color(0,0,0,0));
        btnCancelSaida.setBackground(new Color(0,0,0,0));
        LocalDate dataAtual1 = LocalDate.now();       
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/YYYY");
        String dataTxt = dataAtual1.format(formatter);
        txtData.setText(dataTxt);
        aviso.setVisible(false);
        btnConfirmarEdit.setVisible(false);
        btnCancelSaida.setVisible(false);
        btnDepFixa.setBackground(new Color(0,0,0,0));
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aviso = new javax.swing.JLabel();
        btnConfirmarEdit = new javax.swing.JButton();
        btnCancelSaida = new javax.swing.JButton();
        btnEditSaida = new javax.swing.JButton();
        cbxCategoria = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtTipoInvest = new javax.swing.JTextField();
        txtNome1 = new javax.swing.JTextField();
        txtValor = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JFormattedTextField();
        cbxFixaVariavel = new javax.swing.JComboBox<>();
        cbxAtivoPassivo = new javax.swing.JComboBox<>();
        btnCadSaida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDepFixa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aviso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 0, 0));
        aviso.setText("Atenção você está editanto a saída");
        getContentPane().add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        btnConfirmarEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ConfirmarRed.png"))); // NOI18N
        btnConfirmarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 540, 210, 130));

        btnCancelSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CancelarRed.png"))); // NOI18N
        btnCancelSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 210, 130));

        btnEditSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 210, 130));

        cbxCategoria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercado", "Assinaturas", "Moradia", "Roupa", "Computador", "Carro", "Fast Food", "Transporte", "Uber", "Estudos", "Cuidados Pessoais", "Lazer", "Dívidas", "Investimento", "Outros" }));
        getContentPane().add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 442, 510, 60));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, 96, 37));

        txtTipoInvest.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTipoInvest.setBorder(null);
        txtTipoInvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoInvestActionPerformed(evt);
            }
        });
        getContentPane().add(txtTipoInvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 455, 260, 50));

        txtNome1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNome1.setBorder(null);
        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 213, 510, 50));

        txtValor.setBorder(null);
        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        txtValor.setText("0,00");
        txtValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 331, 470, 50));

        txtData.setBorder(null);
        txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtData.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 208, 260, 60));

        cbxFixaVariavel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxFixaVariavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Variável", "Fixa" }));
        cbxFixaVariavel.setBorder(null);
        cbxFixaVariavel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxFixaVariavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFixaVariavelActionPerformed(evt);
            }
        });
        getContentPane().add(cbxFixaVariavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 565, 350, 60));

        cbxAtivoPassivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxAtivoPassivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passivo", "Ativo", "N/A" }));
        cbxAtivoPassivo.setBorder(null);
        cbxAtivoPassivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxAtivoPassivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAtivoPassivoActionPerformed(evt);
            }
        });
        getContentPane().add(cbxAtivoPassivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 324, 260, 60));

        btnCadSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 200, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("R$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TelaSaida (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnDepFixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DespFixa.png"))); // NOI18N
        btnDepFixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepFixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepFixaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDepFixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 210, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTipoInvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoInvestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoInvestActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void cbxFixaVariavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFixaVariavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFixaVariavelActionPerformed

    private void cbxAtivoPassivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAtivoPassivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAtivoPassivoActionPerformed

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void btnCadSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadSaidaActionPerformed
        String nome = txtNome1.getText();
        String categoria = cbxCategoria.getSelectedItem().toString();
        double valor;
        if(txtValor.getText().isEmpty()){
                 valor = 0.0;
            }
            else{
                 valor = Double.parseDouble(txtValor.getText().replace(".", "").replace(",","."));
            }
        String fixa_variavel = cbxFixaVariavel.getSelectedItem().toString();        
        String Data_Transacao = txtData.getText().substring(6, 10) + "-" 
                                + txtData.getText().substring(3, 5)+ "-"
                                 + txtData.getText().substring(0, 2) ;
  
        String ativo_passivo = cbxAtivoPassivo.getSelectedItem().toString();
        String tipo_invest;
        if(txtTipoInvest.getText().isEmpty()){
                 tipo_invest ="N/A";
            }
            else{
                 tipo_invest = txtTipoInvest.getText();
            }
        DAO dao = new DAO();
        try {
            dao.cadastrarTransacao(tipo, nome, categoria, valor, fixa_variavel, ativo_passivo, Data_Transacao, tipo_invest);
        } catch (Exception ex) {
            Logger.getLogger(TelaEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNome1.setText("");
        cbxCategoria.setSelectedIndex(0);
        cbxFixaVariavel.setSelectedIndex(0);
        LocalDate dataAtual1 = LocalDate.now();       
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/YYYY");
        String dataTxt = dataAtual1.format(formatter);
        txtData.setText(dataTxt);
        txtValor.setText("");
    }//GEN-LAST:event_btnCadSaidaActionPerformed

    private void btnEditSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSaidaActionPerformed
        String verificaResp = JOptionPane.showInputDialog("Qual o ID da venda que você deseja editar?");
        btnConfirmarEdit.setVisible(true);
        btnCancelSaida.setVisible(true);
        btnCadSaida.setVisible(false);       
        btnEditSaida.setVisible(false);
// Verificar se o usuário clicou em "Cancelar" ou fechou a caixa de diálogo
if (verificaResp == null) {
    // Restaurar visibilidade dos botões
    btnConfirmarEdit.setVisible(false);
    btnCancelSaida.setVisible(false);
    btnCadSaida.setVisible(true);
    btnEditSaida.setVisible(true);
} else {
    try {
        DAO dao = new DAO();
        int idMud = Integer.parseInt(verificaResp);
        
        Transferencia transfe = dao.getTransfe(idMud);
        if(!transfe.getEntrada_saida().equals("Saída")){
            JOptionPane.showMessageDialog(null,"O id mencionado não é uma sáida.\n Tente novamente");
            btnConfirmarEdit.setVisible(false);
            btnCancelSaida.setVisible(false);
            btnCadSaida.setVisible(true);
            btnEditSaida.setVisible(true);
        }
        else{
            this.id = idMud;
        
        txtNome1.setText(transfe.getNome());
        txtValor.setText(Double.toString(transfe.getValor()).replace(".", ","));
        cbxCategoria.setSelectedItem(transfe.getCategoria());
        txtData.setText(transfe.getData_Transacao().substring(8, 10) + "/" 
                                + transfe.getData_Transacao().substring(5, 7)+ "/"
                                 + transfe.getData_Transacao().substring(0, 4));
        cbxFixaVariavel.setSelectedItem(transfe.getFixa_Variavel());
        cbxAtivoPassivo.setSelectedItem(transfe.getAtivo_Passivo());
        txtTipoInvest.setText(transfe.getTipo_Investimento());
        aviso.setVisible(true);
        aviso.setText("Atenção você está editando a saída " + idMud);
        }
   
    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(null, "Entrada inválida. Por favor, insira um número válido.");
        btnConfirmarEdit.setVisible(false);
        btnCancelSaida.setVisible(false);
        btnCadSaida.setVisible(true);
        btnEditSaida.setVisible(true);
    } catch (Exception ex) {
        // Tratar exceções ao tentar obter o produto
        JOptionPane.showMessageDialog(null, "Erro ao buscar o produto. Tente novamente.");
        
        // Restaurar visibilidade dos botões
        btnConfirmarEdit.setVisible(false);
        btnCancelSaida.setVisible(false);
        btnCadSaida.setVisible(true);
        btnEditSaida.setVisible(true);
        }
    }   
    }//GEN-LAST:event_btnEditSaidaActionPerformed

    private void btnCancelSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSaidaActionPerformed
        txtNome1.setText("");
        cbxCategoria.setSelectedIndex(0);
        cbxFixaVariavel.setSelectedIndex(0);
        LocalDate dataAtual1 = LocalDate.now();       
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/YYYY");
        String dataTxt = dataAtual1.format(formatter);
        txtData.setText(dataTxt);
        txtValor.setText("");
        aviso.setVisible(false);
        cbxAtivoPassivo.setSelectedIndex(0);
        txtTipoInvest.setText("");
        aviso.setVisible(false);
        btnConfirmarEdit.setVisible(false);
        btnCancelSaida.setVisible(false);
        btnCadSaida.setVisible(true);
        btnEditSaida.setVisible(true);
        
    }//GEN-LAST:event_btnCancelSaidaActionPerformed

    private void btnConfirmarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEditActionPerformed
        String nome = txtNome1.getText();
        String categoria = cbxCategoria.getSelectedItem().toString();
        double valor;
        if(txtValor.getText().isEmpty()){
                 valor = 0.0;
            }
            else{
                 valor = Double.parseDouble(txtValor.getText().replace(".", "").replace(",","."));
            }
        String fixa_variavel = cbxFixaVariavel.getSelectedItem().toString();        
        String Data_Transacao = txtData.getText().substring(6, 10) + "-" 
                                + txtData.getText().substring(3, 5)+ "-"
                                 + txtData.getText().substring(0, 2) ;
  
        String ativo_passivo = cbxAtivoPassivo.getSelectedItem().toString();
        String tipo_invest;
        if(txtTipoInvest.getText().isEmpty()){
                 tipo_invest ="N/A";
            }
            else{
                 tipo_invest = txtTipoInvest.getText();
            }
        DAO dao = new DAO();
        try {
            dao.atualizaTransacao(id,tipo, nome, categoria, valor, fixa_variavel, ativo_passivo, Data_Transacao, tipo_invest);
        } catch (Exception ex) {
            Logger.getLogger(TelaEntrada.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNome1.setText("");
        cbxCategoria.setSelectedIndex(0);
        cbxFixaVariavel.setSelectedIndex(0);
        LocalDate dataAtual1 = LocalDate.now();       
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/YYYY");
        String dataTxt = dataAtual1.format(formatter);
        txtData.setText(dataTxt);
        txtValor.setText("");
        btnConfirmarEdit.setVisible(false);
        btnCancelSaida.setVisible(false);
        btnCadSaida.setVisible(true);
        btnEditSaida.setVisible(true);
        aviso.setVisible(false);
    }//GEN-LAST:event_btnConfirmarEditActionPerformed

    private void btnDepFixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepFixaActionPerformed
      
        DAO dao = new DAO();            
        try {
                dao.insereDespesasFixas();
                        
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDepFixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.JButton btnCadSaida;
    private javax.swing.JButton btnCancelSaida;
    private javax.swing.JButton btnConfirmarEdit;
    private javax.swing.JButton btnDepFixa;
    private javax.swing.JButton btnEditSaida;
    private javax.swing.JComboBox<String> cbxAtivoPassivo;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxFixaVariavel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtTipoInvest;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
