/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaMenu extends javax.swing.JFrame {
    private Usuario logado;
    public TelaMenu() {
        super ("Menu"); 
        initComponents();
        btnMeusCursos.setBackground(new Color (0,0,0,0));
        btnCursosDisp.setBackground(new Color (0,0,0,0));
        btnExtra.setBackground(new Color (0,0,0,0));
        btnMinhasinfo.setBackground(new Color (0,0,0,0));
        btnDesconectar.setBackground(new Color (0,0,0,0));
        setLocationRelativeTo(null);
        
    }
    public TelaMenu(Usuario logado) {
        super ("Menu");
        initComponents();
        btnMeusCursos.setBackground(new Color (0,0,0,0));
        btnCursosDisp.setBackground(new Color (0,0,0,0));
        btnExtra.setBackground(new Color (0,0,0,0));
        btnMinhasinfo.setBackground(new Color (0,0,0,0));
        btnDesconectar.setBackground(new Color (0,0,0,0));        
        setLocationRelativeTo(null);
        txtApresentacao.setText("<html>Olá "+ logado.getNome() +"! Seja bem-vindo ao SYNAPSES,O que você deseja fazer?</html>");
        this.logado = logado;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCursosDisp = new javax.swing.JButton();
        btnMeusCursos = new javax.swing.JButton();
        btnExtra = new javax.swing.JButton();
        btnMinhasinfo = new javax.swing.JButton();
        txtApresentacao = new javax.swing.JLabel();
        btnDesconectar = new javax.swing.JButton();
        imgFundoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCursosDisp.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323378007351366/btnCursosDisp1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnCursosDisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCursosDispMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCursosDispMouseExited(evt);
            }
        });
        btnCursosDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosDispActionPerformed(evt);
            }
        });
        getContentPane().add(btnCursosDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 150, 70));

        btnMeusCursos.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323379055927296/btnMeusCursos.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnMeusCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMeusCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMeusCursosMouseExited(evt);
            }
        });
        btnMeusCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeusCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeusCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 150, 70));

        btnExtra.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323378590359653/btnExtra1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnExtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExtraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExtraMouseExited(evt);
            }
        });
        btnExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraActionPerformed(evt);
            }
        });
        getContentPane().add(btnExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 150, 70));

        btnMinhasinfo.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323379550867467/btnMinhasInfo1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnMinhasinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinhasinfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinhasinfoMouseExited(evt);
            }
        });
        btnMinhasinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinhasinfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinhasinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 150, 70));

        txtApresentacao.setFont(new java.awt.Font("LCD", 0, 24)); // NOI18N
        txtApresentacao.setText("<html>Olá! Seja bem-vindo ao SYNAPSES,O que você deseja fazer?</html>");
        getContentPane().add(txtApresentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, -1));

        btnDesconectar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1114224451173752912/btnDesconectar1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDesconectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDesconectarMouseExited(evt);
            }
        });
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 310, -1, -1));

        imgFundoMenu.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1111061157386662048/TelaMenu_1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgFundoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeusCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeusCursosActionPerformed
        TelaMeusCursos tmc = new TelaMeusCursos(logado);
        tmc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMeusCursosActionPerformed

    private void btnCursosDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosDispActionPerformed
        TelaCursosDisp tcd = new TelaCursosDisp(logado);
        tcd.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCursosDispActionPerformed

    private void btnMinhasinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinhasinfoActionPerformed
        TelaMinhasInfo tmi = new TelaMinhasInfo(logado);
        tmi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMinhasinfoActionPerformed

    private void btnExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraActionPerformed
        TelaExtra te = new TelaExtra(logado);
        te.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExtraActionPerformed

    private void btnMeusCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeusCursosMouseEntered
        btnMeusCursos.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323379299192954/btnMeusCursos2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnMeusCursosMouseEntered

    private void btnMeusCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeusCursosMouseExited
        btnMeusCursos.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323379055927296/btnMeusCursos.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnMeusCursosMouseExited

    private void btnCursosDispMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosDispMouseEntered
         btnCursosDisp.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323378330325082/btnCursosDisp2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnCursosDispMouseEntered

    private void btnCursosDispMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursosDispMouseExited
         btnCursosDisp.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323378007351366/btnCursosDisp1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnCursosDispMouseExited

    private void btnMinhasinfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinhasinfoMouseEntered
        btnMinhasinfo.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323377688596520/btnMinhasInfo2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnMinhasinfoMouseEntered

    private void btnMinhasinfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinhasinfoMouseExited
        btnMinhasinfo.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323379550867467/btnMinhasInfo1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnMinhasinfoMouseExited

    private void btnExtraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtraMouseEntered
        btnExtra.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323378804281384/btnExtra2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnExtraMouseEntered

    private void btnExtraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtraMouseExited
        btnExtra.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1113323378590359653/btnExtra1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnExtraMouseExited

    private void btnDesconectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesconectarMouseEntered
        btnDesconectar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1114224451383472179/btnDesconectar2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnDesconectarMouseEntered

    private void btnDesconectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesconectarMouseExited
        btnDesconectar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1114224451173752912/btnDesconectar1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnDesconectarMouseExited

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursosDisp;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnExtra;
    private javax.swing.JButton btnMeusCursos;
    private javax.swing.JButton btnMinhasinfo;
    private javax.swing.JLabel imgFundoMenu;
    private javax.swing.JLabel txtApresentacao;
    // End of variables declaration//GEN-END:variables
}
