/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author andre
 */
public class CadastroVendas extends javax.swing.JFrame {
    DAO dao = new DAO();
    int idMud = 0;
    int qtdAntiga = 0;
    /**
     * Creates new form CadastroVendas
     */
    public CadastroVendas() {
        initComponents();
        try{
            this.tblUltimasVendas.setModel(new TodasVendas());
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde.");
        }
        String[] produtos = null;
        try {
            produtos = dao.obterProdutos();
        } catch (Exception ex) {
            Logger.getLogger(CadastroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String produto : produtos) {
                cbxProduto.addItem(produto);
        }
        setLocationRelativeTo(null);
        btnCadVenda.setBackground(new Color(0,0,0,0));
        btnEditVenda.setBackground(new Color(0,0,0,0));
        btnRemVenda.setBackground(new Color(0,0,0,0));
        
        txtFaltaPagar.setBackground(new Color(0,0,0,0));
        txtNomeComprador.setBackground(new Color(0,0,0,0));
        cbxProduto.setBackground(new Color(0,0,0,0));
        cbxFormaPag.setBackground(new Color(0,0,0,0));
        btnConfirmaEdit.setVisible(false);
        btnCancelaEdit.setVisible(false);
        aviso.setVisible(false);
        TableColumnModel columnModel = tblUltimasVendas.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(180);
        columnModel.getColumn(3).setPreferredWidth(20);
        columnModel.getColumn(4).setPreferredWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aviso = new javax.swing.JLabel();
        btnConfirmaEdit = new javax.swing.JButton();
        btnCancelaEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUltimasVendas = new javax.swing.JTable();
        txtFaltaPagar = new javax.swing.JFormattedTextField();
        txtNomeComprador = new javax.swing.JTextField();
        cbxFormaPag = new javax.swing.JComboBox<>();
        cbxProduto = new javax.swing.JComboBox<>();
        spnQtdProd = new javax.swing.JSpinner();
        btnCadVenda = new javax.swing.JButton();
        btnRemVenda = new javax.swing.JButton();
        btnEditVenda = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aviso.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 0, 0));
        aviso.setText("Atenção você está editando a venda 11111");
        getContentPane().add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, -1));

        btnConfirmaEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnConfirmarEdicao.png"))); // NOI18N
        btnConfirmaEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 120, 75));

        btnCancelaEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnCancelarEdicao.png"))); // NOI18N
        btnCancelaEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 120, 75));

        jScrollPane1.setAutoscrolls(true);

        tblUltimasVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblUltimasVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUltimasVendas.setRowHeight(25);
        tblUltimasVendas.setShowGrid(true);
        tblUltimasVendas.setTableHeader(null);
        jScrollPane1.setViewportView(tblUltimasVendas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 150, 758, 530));

        txtFaltaPagar.setBorder(null);
        txtFaltaPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        txtFaltaPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtFaltaPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 520, 340, 40));

        txtNomeComprador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeComprador.setBorder(null);
        getContentPane().add(txtNomeComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 173, 380, 40));

        cbxFormaPag.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxFormaPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Pix", "Dinheiro" }));
        cbxFormaPag.setBorder(null);
        cbxFormaPag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cbxFormaPag, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 433, 380, 40));

        cbxProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxProduto.setBorder(null);
        cbxProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cbxProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 260, 380, 40));

        spnQtdProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spnQtdProd.setBorder(null);
        getContentPane().add(spnQtdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 342, 385, 50));

        btnCadVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnCadVenda.png"))); // NOI18N
        btnCadVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 120, 75));

        btnRemVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnRemVenda.png"))); // NOI18N
        btnRemVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 120, 75));

        btnEditVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnEditaVenda.png"))); // NOI18N
        btnEditVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 120, 75));

        jButton4.setText("Voltar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoCadastroVendas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVendaActionPerformed
        boolean VerificaCliente = false;
        String nomeCliente = txtNomeComprador.getText();
        try {
            String[] clientes = dao.obterClientes();
            for (String cliente : clientes) {
                if(cliente.equals(nomeCliente)){
                    VerificaCliente = true;
                }
            
            }
        } catch (Exception ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(VerificaCliente==false){
            int confirmaCad = JOptionPane.showConfirmDialog(null, "O cliente "+ nomeCliente +" ainda não está cadastrado.\n Você deseja cadastra-lo?");
            if(confirmaCad == 0){
                try {
                    dao.cadastrarCliente(nomeCliente);
                } catch (Exception ex) {
                    Logger.getLogger(CadastroVendas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        try {
            int id_comprador = dao.pegaCliente(nomeCliente).getCodCliente();
            int id_produto = dao.pegaProdutoNome(cbxProduto.getSelectedItem().toString()).getId();

            int qtd = Integer.parseInt(spnQtdProd.getValue().toString());
            String pagamento = cbxFormaPag.getSelectedItem().toString();
            LocalDate dataAtual = LocalDate.now();       
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String data = dataAtual.format(formatter);
            Double FaltaPagar;
            if(txtFaltaPagar.getText().isEmpty()){
                 FaltaPagar = 0.0;
            }
            else{
                 FaltaPagar = Double.valueOf(txtFaltaPagar.getText().replace(",","."));
            }
            
            
            
        dao.cadastrarVenda(id_comprador,id_produto,qtd, pagamento, data,FaltaPagar);
        this.tblUltimasVendas.setModel(new TodasVendas());
        TableColumnModel columnModel = tblUltimasVendas.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(180);
        columnModel.getColumn(3).setPreferredWidth(20);
        columnModel.getColumn(4).setPreferredWidth(50);
        } catch (Exception ex) {
            Logger.getLogger(CadastroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomeComprador.setText("");
        cbxProduto.setSelectedIndex(0);
        spnQtdProd.setValue(0);
        cbxFormaPag.setSelectedIndex(0);
        txtFaltaPagar.setText("");
        
        
    }//GEN-LAST:event_btnCadVendaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnRemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemVendaActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog("Qual o ID do venda que você deseja apagar?"));
        
        try {
            dao.removerVenda(id);
            this.tblUltimasVendas.setModel(new TodasVendas());
            TableColumnModel columnModel = tblUltimasVendas.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(180);
        columnModel.getColumn(3).setPreferredWidth(20);
        columnModel.getColumn(4).setPreferredWidth(50);
        } catch(java.sql.SQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(null, "Não foi possível remover a compra. Tente edita-la");
        }
        catch (Exception ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemVendaActionPerformed

    private void btnConfirmaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaEditActionPerformed
        btnCadVenda.setVisible(true);
        btnRemVenda.setVisible(true);
        btnEditVenda.setVisible(true);
        btnConfirmaEdit.setVisible(false);
        btnCancelaEdit.setVisible(false);
       String nomeCliente = txtNomeComprador.getText();
       try {
            int id_comprador = dao.pegaCliente(nomeCliente).getCodCliente();
            int id_produto = dao.pegaProdutoNome(cbxProduto.getSelectedItem().toString()).getId();

            int qtd = Integer.parseInt(spnQtdProd.getValue().toString());
            String pagamento = cbxFormaPag.getSelectedItem().toString();
            System.out.println(pagamento);
            Double FaltaPagar;
            if(txtFaltaPagar.getText().isEmpty()){
                 FaltaPagar = 0.0;
            }
            else{
                 FaltaPagar = Double.valueOf(txtFaltaPagar.getText().replace(",","."));
            }
                 
        dao.editaVenda(qtdAntiga,idMud,id_comprador,id_produto,qtd, pagamento,FaltaPagar);
        this.tblUltimasVendas.setModel(new TodasVendas());
        TableColumnModel columnModel = tblUltimasVendas.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(180);
        columnModel.getColumn(3).setPreferredWidth(20);
        columnModel.getColumn(4).setPreferredWidth(50);
        } catch (Exception ex) {
            Logger.getLogger(CadastroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        aviso.setVisible(false);
        txtNomeComprador.setText("");
        cbxProduto.setSelectedIndex(0);
        spnQtdProd.setValue(0);
        cbxFormaPag.setSelectedIndex(0);
        txtFaltaPagar.setText("");
    }//GEN-LAST:event_btnConfirmaEditActionPerformed

    private void btnCancelaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaEditActionPerformed
        txtNomeComprador.setText("");
        cbxProduto.setSelectedIndex(0);
        spnQtdProd.setValue(0);
        cbxFormaPag.setSelectedIndex(0);
        txtFaltaPagar.setText("");
        btnCadVenda.setVisible(true);
        btnRemVenda.setVisible(true);
        btnEditVenda.setVisible(true);
        btnConfirmaEdit.setVisible(false);
        btnCancelaEdit.setVisible(false);
        aviso.setVisible(false);
    }//GEN-LAST:event_btnCancelaEditActionPerformed

    private void btnEditVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditVendaActionPerformed
    btnCadVenda.setVisible(false);
    btnRemVenda.setVisible(false);
    btnEditVenda.setVisible(false);
    btnConfirmaEdit.setVisible(true);
    btnCancelaEdit.setVisible(true);

// Exibir caixa de diálogo para obter o ID do produto
String verificaResp = JOptionPane.showInputDialog("Qual o ID da venda que você deseja editar?");

// Verificar se o usuário clicou em "Cancelar" ou fechou a caixa de diálogo
if (verificaResp == null) {
    // Restaurar visibilidade dos botões
    btnCadVenda.setVisible(true);
    btnRemVenda.setVisible(true);
    btnEditVenda.setVisible(true);
    btnConfirmaEdit.setVisible(false);
    btnCancelaEdit.setVisible(false);
} else {
    try {
        idMud = Integer.parseInt(verificaResp);
        Vendas venda = dao.pegaVenda(idMud);
        txtNomeComprador.setText(venda.getNomeComprador());
        cbxProduto.setSelectedItem(venda.getNomeProduto());
        spnQtdProd.setValue(venda.getQtd_Produto());
        qtdAntiga = venda.getQtd_Produto();
        cbxFormaPag.setSelectedItem(venda.getForma_pagamento());
        txtFaltaPagar.setText(Double.toString(venda.getFalta_pagar()).replace(".", ","));
        aviso.setVisible(true);
        aviso.setText("Atenção você está editando a venda " + idMud);
   
    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(null, "Entrada inválida. Por favor, insira um número válido.");
        btnCadVenda.setVisible(true);
        btnRemVenda.setVisible(true);
        btnEditVenda.setVisible(true);
        btnConfirmaEdit.setVisible(false);
        btnCancelaEdit.setVisible(false);
    } catch (Exception ex) {
        // Tratar exceções ao tentar obter o produto
        Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Erro ao buscar o produto. Tente novamente.");
        
        // Restaurar visibilidade dos botões
        btnCadVenda.setVisible(true);
        btnRemVenda.setVisible(true);
        btnEditVenda.setVisible(true);
        btnConfirmaEdit.setVisible(false);
        btnCancelaEdit.setVisible(false);
        }
    }
    }//GEN-LAST:event_btnEditVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.JButton btnCadVenda;
    private javax.swing.JButton btnCancelaEdit;
    private javax.swing.JButton btnConfirmaEdit;
    private javax.swing.JButton btnEditVenda;
    private javax.swing.JButton btnRemVenda;
    private javax.swing.JComboBox<String> cbxFormaPag;
    private javax.swing.JComboBox<String> cbxProduto;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnQtdProd;
    private javax.swing.JTable tblUltimasVendas;
    private javax.swing.JFormattedTextField txtFaltaPagar;
    private javax.swing.JTextField txtNomeComprador;
    // End of variables declaration//GEN-END:variables
}
