/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andre
 */
public class TelaPrincipal extends javax.swing.JFrame {
     DAO dao = new DAO();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        btnCadastrarProduto.setBackground(new Color(0,0,0,0));
        btnCadastrarVendas.setBackground(new Color(0,0,0,0));
        btnBanco.setBackground(new Color(0,0,0,0));
         try {
             String lucro = dao.obtemLucro(); // Obtém o valor original
            lucro = lucro.replace(",", "."); // Substitui a vírgula por ponto
            double valorLucro = Double.parseDouble(lucro); // Converte para double
            String lucroFormatado = String.format("%.2f", valorLucro); // Formata com 2 casas decimais
            lucroFormatado = lucroFormatado.replace(".", ","); 
             jlbLucro.setText(lucroFormatado);
         } catch (Exception ex) {
             Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbLucro = new javax.swing.JLabel();
        btnCadastrarProduto = new javax.swing.JToggleButton();
        btnCadastrarVendas = new javax.swing.JToggleButton();
        btnBanco = new javax.swing.JToggleButton();
        btnVisualizarVendas1 = new javax.swing.JToggleButton();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLucro.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        jlbLucro.setText("jLabel1");
        getContentPane().add(jlbLucro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnCadProdNovo.png"))); // NOI18N
        btnCadastrarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 250, 130));

        btnCadastrarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnCadVendaInic.png"))); // NOI18N
        btnCadastrarVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVendasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 240, 130));

        btnBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnVisuBanco.png"))); // NOI18N
        btnBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, 240, 130));

        btnVisualizarVendas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnVisuVendas.png"))); // NOI18N
        btnVisualizarVendas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualizarVendas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarVendas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisualizarVendas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 240, 130));

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoTelaPrincipal.png"))); // NOI18N
        getContentPane().add(imgFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        CadastroProduto CP = new CadastroProduto();
        CP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnCadastrarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVendasActionPerformed
        CadastroVendas CDV = new CadastroVendas();
        CDV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarVendasActionPerformed

    private void btnBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancoActionPerformed
        TelaBanco tb = new TelaBanco();
        tb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBancoActionPerformed

    private void btnVisualizarVendas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarVendas1ActionPerformed
        TelaVisualizarVendas tvv = new TelaVisualizarVendas();
        tvv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVisualizarVendas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBanco;
    private javax.swing.JToggleButton btnCadastrarProduto;
    private javax.swing.JToggleButton btnCadastrarVendas;
    private javax.swing.JToggleButton btnVisualizarVendas1;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel jlbLucro;
    // End of variables declaration//GEN-END:variables
}
