/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package;

import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author andre
 */
public class TelaBanco extends javax.swing.JFrame {
     DAO dao = new DAO();
    /**
     * Creates new form TelaBanco
     */
    public TelaBanco() {
        initComponents();
        setLocationRelativeTo(null);
        try{
            this.tblDinheiro.setModel(new TodasVendasFiltro(0));
            TableColumnModel columnModel = tblDinheiro.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(100);
            columnModel.getColumn(1).setPreferredWidth(200);
            columnModel.getColumn(2).setPreferredWidth(10);
            columnModel.getColumn(3).setPreferredWidth(50);
            columnModel.getColumn(4).setPreferredWidth(60);
            columnModel.getColumn(5).setPreferredWidth(30);
            this.tblPix.setModel(new TodasVendasFiltro(1));
            TableColumnModel columnMode2 = tblPix.getColumnModel();
            columnMode2.getColumn(0).setPreferredWidth(100);
            columnMode2.getColumn(1).setPreferredWidth(200);
            columnMode2.getColumn(2).setPreferredWidth(10);
            columnMode2.getColumn(3).setPreferredWidth(50);
            columnMode2.getColumn(4).setPreferredWidth(60);
            columnMode2.getColumn(5).setPreferredWidth(30);
            lucroDin.setText(dao.obtemValorDinheiro());
            lucroPix.setText(dao.obtemValorPix());
            double total = Double.valueOf(dao.obtemValorDinheiro().replace(",", "."))+ Double.valueOf(dao.obtemValorPix().replace(",", "."));
            valorTotal.setText("R$ " + Double.toString(total).replace(".",","));
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde.");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        valorTotal = new javax.swing.JLabel();
        lucroPix = new javax.swing.JLabel();
        lucroDin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPix = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDinheiro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Voltar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        valorTotal.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        valorTotal.setText("R$ ");
        getContentPane().add(valorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        lucroPix.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lucroPix.setText("jLabel2");
        getContentPane().add(lucroPix, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, -1, -1));

        lucroDin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lucroDin.setText("jLabel2");
        getContentPane().add(lucroDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, -1, -1));

        tblPix.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPix.setRowHeight(25);
        tblPix.setShowGrid(true);
        tblPix.setTableHeader(null);
        jScrollPane1.setViewportView(tblPix);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 202, 554, 420));

        tblDinheiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDinheiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDinheiro.setRowHeight(25);
        tblDinheiro.setShowGrid(true);
        tblDinheiro.setTableHeader(null);
        jScrollPane2.setViewportView(tblDinheiro);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 202, 554, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoBanco.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lucroDin;
    private javax.swing.JLabel lucroPix;
    private javax.swing.JTable tblDinheiro;
    private javax.swing.JTable tblPix;
    private javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables
}
