/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaAumentarLimite extends javax.swing.JFrame {
    private User logado;
    /**
     * Creates new form TelaAumentarLimite
     */
    public TelaAumentarLimite(User logado) {
        super("Aumentar limite");
        try {
            initComponents();
            this.logado = logado;
            setLocationRelativeTo(null);
            btnVoltar.setBackground(new Color(0,0,0,0));
            btnSolicitar.setBackground(new Color(0,0,0,0));
            txtRenda.setBackground(new Color(0,0,0,0));
            DAO dao = new DAO();
            String limite = Double.toString(dao.verificaLimite(logado.getCodConta()));
            int index = limite.indexOf(".")+1;
            String aposvirgula = limite.substring(index, limite.length());
            String valorCerto = limite.replace('.',',');
            if(aposvirgula.length() == 1){
                valorCerto = (limite+ '0').replace('.',',');
            }
            else{
                valorCerto = limite.replace('.',',');
            }
            txtvalor.setText(valorCerto);
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    dispose();
                }
            });    
        } catch (Exception ex) {
            Logger.getLogger(TelaAumentarLimite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public TelaAumentarLimite() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JLabel();
        txtRenda = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnSolicitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("R$");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 469, 20, 40));

        txtvalor.setFont(new java.awt.Font("Dialog", 0, 54)); // NOI18N
        txtvalor.setForeground(new java.awt.Color(255, 255, 255));
        txtvalor.setText("00,00");
        getContentPane().add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 253, -1, 60));

        txtRenda.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtRenda.setBorder(null);
        getContentPane().add(txtRenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 470, 307, 40));

        btnVoltar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/Arrow%201.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 30));

        btnSolicitar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnSolicitar.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSolicitarMouseExited(evt);
            }
        });
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 537, 110, 40));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/FundoTelaAumentarLmt.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
                this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        try {
            String txtvalor = txtRenda.getText();
            String txtValorCerto = txtvalor.replace(',', '.');
            double valor = Double.parseDouble(txtValorCerto);
            double limite = valor * 2.3;
            DAO dao = new DAO();
            double verificalimite = dao.verificaLimite(logado.getCodConta());
            if(limite<verificalimite){
                int tipo = 7;
                TelaAvisos2 ta = new TelaAvisos2(tipo);
                ta.setVisible(true);               
            }
            else{
                boolean confirmacao = dao.AumetarLimite(limite, logado);
                if(confirmacao){
                    int tipo = 6;
                    TelaAvisos2 ta = new TelaAvisos2(tipo,Double.toString(limite).replace('.',','));
                    ta.setVisible(true);                    

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaAumentarLimite.class.getName()).log(Level.SEVERE, null, ex);
            int tipo = 12;
                TelaAvisos ta = new TelaAvisos(tipo);
                ta.setVisible(true);
        }
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void btnSolicitarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseEntered
        btnSolicitar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnSolicitar2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnSolicitarMouseEntered

    private void btnSolicitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarMouseExited
        btnSolicitar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnSolicitar.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnSolicitarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAumentarLimite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAumentarLimite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAumentarLimite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAumentarLimite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAumentarLimite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtRenda;
    private javax.swing.JLabel txtvalor;
    // End of variables declaration//GEN-END:variables
}
