/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaCadastrarPix extends javax.swing.JFrame {
    private User logado;
    /**
     * Creates new form TelaCadastrarPix
     */
    public TelaCadastrarPix(User logado) {
            super("Cadastrar Chave-Pix");
            initComponents();
            txtChave.setBackground(new Color (0,0,0,0));
            txtConfirmaChave.setBackground(new Color (0,0,0,0));
            btnCadastrar.setBackground(new Color (0,0,0,0));
            btnVoltar.setBackground(new Color (0,0,0,0));
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    dispose();
                }
            });    
            this.logado = logado;
            txtChave.setText(logado.getEmail());
            setLocationRelativeTo(null);
            cbTipoChave.setBackground(new Color(0,0,0,0));
    }

    public TelaCadastrarPix() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txtConfirmaChave = new javax.swing.JTextField();
        txtChave = new javax.swing.JTextField();
        cbTipoChave = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/Arrow%201.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 30));

        btnCadastrar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnCadastrarPeq.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 473, 110, 40));

        txtConfirmaChave.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtConfirmaChave.setBorder(null);
        getContentPane().add(txtConfirmaChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 405, 332, 40));

        txtChave.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtChave.setBorder(null);
        getContentPane().add(txtChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 325, 332, 40));

        cbTipoChave.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cbTipoChave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Email", "Telefone", "CPF", " " }));
        cbTipoChave.setBorder(null);
        cbTipoChave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbTipoChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoChaveActionPerformed(evt);
            }
        });
        getContentPane().add(cbTipoChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 242, 332, 45));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/FundoTelaCadastraPix.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoChaveActionPerformed
        String escolha = cbTipoChave.getSelectedItem().toString();
        if(escolha.equals("Email")){
            txtChave.setText(logado.getEmail());
        }
        else if(escolha.equals("Telefone")){
            txtChave.setText(logado.getTelefone());    
        }
        else if(escolha.equals("CPF")){
            txtChave.setText(logado.getCpf());
        }
    }//GEN-LAST:event_cbTipoChaveActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            DAO dao = new DAO();
            String chaveCadastrada = dao.verificaChavePix(logado.getCodConta());
            String chave2 = txtConfirmaChave.getText();
            String chave1 = txtChave.getText();
            ArrayList<String> todasChaves = dao.todasChavesPix();
            if(chaveCadastrada.equals(" ")){
                if(chave1.equals(chave2)){
                    if(todasChaves.contains(chave2)){
                        
                        int tipo = 8;
                        TelaAvisos ta = new TelaAvisos(tipo);
                        ta.setVisible(true);
                    }
                    else{
                        dao.cadastrarChavePIx(logado, chave2);
                        
                        int tipo = 9;
                        TelaAvisos2 ta = new TelaAvisos2(tipo);
                        ta.setVisible(true);
                    }
                }
                else{
                    
                    int tipo = 10;
                        TelaAvisos ta = new TelaAvisos(tipo);
                        ta.setVisible(true);
                }
            }
            else{
              
            int tipo = 11;
                        TelaAvisos ta = new TelaAvisos(tipo);
                        ta.setVisible(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastrarPix.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
        btnCadastrar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnCadastrarPeq2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        btnCadastrar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnCadastrarPeq.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnCadastrarMouseExited

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarPix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbTipoChave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtChave;
    private javax.swing.JTextField txtConfirmaChave;
    // End of variables declaration//GEN-END:variables
}
