/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author andre
 */
public class TelaCadastro2 extends javax.swing.JFrame {
    private User userCad;
    private User userCad2;
    
    private int cod;
    /**
     * Creates new form TelaCadastro2
     * @param userCad
     */
    public TelaCadastro2(User userCad) {
        super("Cadastro");
        initComponents();
        setLocationRelativeTo(null);
        this.userCad = userCad;
        User userCad2 = new User(userCad.getNome(),userCad.getCpf(),userCad.getCep(),userCad.getEmail(),userCad.getTelefone());
        btnVoltar.setBackground(new Color(0,0,0,0));
        cbNacionalidade.setBackground(new Color(0,0,0,0));
        pswSenha1.setBackground(new Color(0,0,0,0));
        pswSenha2.setBackground(new Color(0,0,0,0));
        txtNascimento.setBackground(new Color(0,0,0,0));
        lblData.setVisible(false);
        lblSenha.setVisible(false);
    }

    private TelaCadastro2() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenha = new javax.swing.JLabel();
        lblData1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JFormattedTextField();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        pswSenha1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        pswSenha2 = new javax.swing.JPasswordField();
        cbNacionalidade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSenha.setForeground(new java.awt.Color(255, 0, 0));
        lblSenha.setText("Senha inválida");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 438, -1, -1));

        lblData1.setForeground(new java.awt.Color(255, 255, 255));
        lblData1.setText("(4 digítos numéricos)");
        getContentPane().add(lblData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        lblData.setForeground(new java.awt.Color(255, 0, 0));
        lblData.setText("Data inválida");
        getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 273, -1, -1));

        txtNascimento.setBorder(null);
        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 296, 330, 40));

        btnVoltar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/Arrow%201.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 30));

        btnCadastrar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnCadastrarPeq.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 633, 98, 35));

        pswSenha1.setBorder(null);
        getContentPane().add(pswSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 473, 330, 40));

        jLabel3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/DtNascimento.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 293, -1, -1));

        pswSenha2.setBorder(null);
        getContentPane().add(pswSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 563, 330, 40));

        cbNacionalidade.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cbNacionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brasil", "EUA", "Argentina", "Portugal", "Canadá" }));
        cbNacionalidade.setBorder(null);
        cbNacionalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cbNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 382, 330, 45));

        jLabel2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1121027572541685781/Rectangle_19.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 293, -1, -1));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/FundoTelaCadastro2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
        btnCadastrar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnCadastrarPeq2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        btnCadastrar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnCadastrarPeq.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnCadastrarMouseExited

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        TelaCadastro tc = new TelaCadastro(userCad);
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String psw = new String(pswSenha1.getPassword());        
        boolean contemLetras = false;
        for (int i = 0; i < psw.length(); i++) {
            if (Character.isLetter(psw.charAt(i))) {
                contemLetras = true;
                break;
            }
        }
        String data = txtNascimento.getText();
        int dia = Integer.parseInt(data.substring(0, 2));
        int mes = Integer.parseInt(data.substring(3, 5));
        int ano= Integer.parseInt(data.substring(6, data.length()));
        if(dia >= 32 || mes>= 13 || ano >= 2024){
        lblData.setVisible(true);    
        }
        else if(contemLetras || psw.length() != 4){
        lblSenha.setVisible(true);
        }
        else{
            try {
                String nome = userCad.getNome();
                String cpf = userCad.getCpf();
                String cep = userCad.getCep();
                String email = userCad.getEmail();
                String telefone = userCad.getTelefone();
                String nacionalidade = cbNacionalidade.getSelectedItem().toString();
                String nascimento = txtNascimento.getText();            
                String senha = new String(pswSenha1.getPassword());
                String senha2 = new String(pswSenha2.getPassword());
                DAO dao = new DAO();
                ArrayList<String> todosCPFs = dao.todosCpfs();
                ArrayList<String> todosTelefones = dao.todosTelefones();
                ArrayList<String> todosEmails = dao.todosEmails();
                if(todosCPFs.contains(cpf)){                
                    int tipo = 15;
                    TelaAvisos ta = new TelaAvisos(tipo);
                    ta.setVisible(true);
                }
                else if(todosEmails.contains(email)){                
                    int tipo = 16;
                    TelaAvisos ta = new TelaAvisos(tipo);
                    ta.setVisible(true);
                }
                else if(todosTelefones.contains(telefone)){                
                    int tipo = 17;
                    TelaAvisos ta = new TelaAvisos(tipo);
                    ta.setVisible(true);
                }
                else{
                    this.cod = 1;
                    Random aleatorio = new Random();
                    if(nome.equals("")|| cpf.equals("")||cep.equals("")||email.equals("")||telefone.equals("")||nacionalidade.equals("")||nascimento.equals("")||senha.equals("")||senha2.equals("")){
                        int tipo = 2;
                        TelaAvisos ta = new TelaAvisos(tipo);
                        ta.setVisible(true);
                    }
                    else{
                        if(senha.equals(senha2)){
                            try {
                                ArrayList <Integer> todascontas = dao.todasContas();
                                while(todascontas.contains(this.cod)){
                                    this.cod = aleatorio.nextInt(1000, 9999);
                                    if(todascontas.size()>= 89999){
                                        int tipo = 3;
                                        TelaAvisos ta = new TelaAvisos(tipo);
                                        ta.setVisible(true);
                                        break;
                                    }
                                }

                                String informaConta = dao.cadastrar(nome, cpf, cep, email, telefone, nascimento, nacionalidade, senha,this.cod);
                                TelaPosCad tpc = new TelaPosCad(informaConta);
                                tpc.setVisible(true);
                                this.dispose();
                            }
                            catch (Exception ex) {
                                ex.printStackTrace();
                                int tipo = 4;
                                TelaAvisos ta = new TelaAvisos(tipo);
                                ta.setVisible(true);
                            }
                        }    
                        else{
                            int tipo = 5;
                            TelaAvisos ta = new TelaAvisos(tipo);
                            ta.setVisible(true);
                        }
                    }
                } 
            }
            catch (Exception ex) {
                Logger.getLogger(TelaCadastro2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCadastro2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbNacionalidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField pswSenha1;
    private javax.swing.JPasswordField pswSenha2;
    private javax.swing.JFormattedTextField txtNascimento;
    // End of variables declaration//GEN-END:variables
}
