/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andre
 */
public class TelaExtrato extends javax.swing.JFrame {
    private User logado;
    /**
     * Creates new form TelaExtrato
     */
    public TelaExtrato(User logado) {
        super("Extrato");
        try {
            initComponents();
            taTransfe.setBackground(new Color(0,0,0,0));
            scrollextrato.setBackground(new Color(0,0,0,0));
            btnVoltar.setBackground(new Color(0,0,0,0));
            setLocationRelativeTo(null);
            String transfe = "";            
            this.logado = logado;
            DAO dao = new DAO();
            ArrayList<Transferencia> todasTransfe = dao.todastTransfeUsuario(logado.getCodConta());
            int tamanho = todasTransfe.size();
            
            for(int i =0;i<tamanho;i++){
                String valor = Double.toString(todasTransfe.get(i).getValor());
                int index = valor.indexOf(".")+1;
                String aposvirgula = valor.substring(index, valor.length());
                String valorCerto = valor.replace('.',',');
                if(aposvirgula.length() == 1){
                    valorCerto = (valor + '0').replace('.',',');
                }
                else{
                    valorCerto = valor.replace('.',',');
                }
            
                if(todasTransfe.get(i).getTipo().equals("Depósito")||todasTransfe.get(i).getTipo().equals("Depósito        ")){
                    String preparatransfe = ( "   Data: " + (todasTransfe.get(i).getDia())+"     "+ todasTransfe.get(i).getTipo()+ "     R$ "+ valorCerto + "                   + CRÉDITO\n");
                    transfe += preparatransfe;
                }
                if(todasTransfe.get(i).getTipo().equals("Investimento")||todasTransfe.get(i).getTipo().equals("Investimento      ")){
                    String preparatransfe = ( "   Data: " + (todasTransfe.get(i).getDia())+"     "+ todasTransfe.get(i).getTipo()+ "     R$ "+valorCerto+ "         - DÉBITO\n");
                    transfe += preparatransfe;
                }
                if(todasTransfe.get(i).getTipo().equals("Pix                  ")&&todasTransfe.get(i).getDestinatario()!= logado.getCodConta()){
                    String preparatransfe = ( "   Data: " + (todasTransfe.get(i).getDia())+"     "+ todasTransfe.get(i).getTipo()+ "     R$ "+valorCerto+ "                - DÉBITO\n");
                    transfe += preparatransfe;
                }
                if(todasTransfe.get(i).getTipo().equals("Pix                  ")&&todasTransfe.get(i).getDestinatario()== logado.getCodConta()){
                    String preparatransfe = ( "   Data: " + (todasTransfe.get(i).getDia())+"     "+ todasTransfe.get(i).getTipo()+ "     R$ "+valorCerto+ "                + CRÉDITO\n");
                    transfe += preparatransfe;
                }
                if(todasTransfe.get(i).getTipo().equals("Transferência")&&todasTransfe.get(i).getDestinatario()!= logado.getCodConta()){
                    String preparatransfe = ( "   Data: " + (todasTransfe.get(i).getDia())+"     "+ todasTransfe.get(i).getTipo()+ "     R$ "+valorCerto+ "         - DÉBITO\n");
                    transfe += preparatransfe;
                }
                if(todasTransfe.get(i).getTipo().equals("Transferência")&&todasTransfe.get(i).getDestinatario()== logado.getCodConta()){
                    String preparatransfe = ( "   Data: " + (todasTransfe.get(i).getDia())+"     "+ todasTransfe.get(i).getTipo()+ "     R$ "+valorCerto+ "         + CRÉDITO\n");
                    transfe += preparatransfe;
                }
                
           
            }
            
            taTransfe.setText(transfe);
        } catch (Exception ex) {
            Logger.getLogger(TelaExtrato.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    public TelaExtrato(){
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        scrollextrato = new javax.swing.JScrollPane();
        taTransfe = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/Arrow%201.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 40, -1));

        scrollextrato.setBorder(null);
        scrollextrato.setOpaque(false);

        taTransfe.setEditable(false);
        taTransfe.setColumns(20);
        taTransfe.setRows(5);
        taTransfe.setBorder(null);
        taTransfe.setOpaque(false);
        scrollextrato.setViewportView(taTransfe);

        getContentPane().add(scrollextrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 410, 660));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/FundoTelaExtrato.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        
        try {
            TelaPrincipal tp = new TelaPrincipal(logado);
            tp.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaExtrato.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExtrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollextrato;
    private javax.swing.JTextArea taTransfe;
    // End of variables declaration//GEN-END:variables
}
