/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaPix extends javax.swing.JFrame {
    private User logado;
    private boolean confirmacao;
    /**
     * Creates new form TelaPix
     */
    public TelaPix(User logado) {
        super("Pix");
        initComponents();
        this.logado = logado;
        btnVoltar.setBackground(new Color(0,0,0,0));
        txtPix.setBackground(new Color(0,0,0,0));
        txtValor.setBackground(new Color(0,0,0,0));
        txtDesc.setBackground(new Color(0,0,0,0));
        btnEnviar.setBackground(new Color(0,0,0,0));
        setLocationRelativeTo(null);
    }
     public TelaPix(boolean confirmacao,User logado,double valor,int destinatario,String descricao,double saldofinaldest,String chave) {
        super("Depósito");
        this.logado = logado;
        this.confirmacao = confirmacao;
        initComponents();
        this.logado = logado;
        btnVoltar.setBackground(new Color(0,0,0,0));
        btnEnviar.setBackground(new Color(0,0,0,0));
        txtPix.setBackground(new Color(0,0,0,0));
        txtValor.setBackground(new Color(0,0,0,0));
        txtDesc.setBackground(new Color(0,0,0,0));
        setLocationRelativeTo(null);
        DAO dao = new DAO();
        int id = 1;      
        if(confirmacao){
                LocalDate dataAtual = LocalDate.now();
                String data = dataAtual.toString();
                
                try {
                    double novoSaldo = logado.getSaldo() - valor;
                    logado.setSaldo(novoSaldo);
                    ArrayList listaId = dao.todasTransferencias();
                    while(listaId.contains(id)){
                        id++;
                    }
                    dao.fazerPix(id,valor,data, logado,novoSaldo,destinatario,descricao,saldofinaldest,chave);                   
                } catch (Exception ex) {
                    Logger.getLogger(TelaDeposito.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            this.confirmacao = false;
        
    }

    public TelaPix() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        txtDesc = new javax.swing.JTextField();
        txtPix = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setText("R$");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 507, 20, 40));

        btnEnviar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnEnviar.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnviarMouseExited(evt);
            }
        });
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 589, 100, 38));

        txtDesc.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtDesc.setBorder(null);
        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        getContentPane().add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 422, 330, 40));

        txtPix.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtPix.setBorder(null);
        txtPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPixActionPerformed(evt);
            }
        });
        getContentPane().add(txtPix, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 336, 330, 40));

        txtValor.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtValor.setBorder(null);
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 508, 307, 40));

        btnVoltar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/Arrow%201.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 40, -1));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/FundoTelaPix.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            TelaPrincipal tp = new TelaPrincipal(logado);
            tp.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPix.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPixActionPerformed
        btnEnviar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1124346651302174830/Group_23_3.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_txtPixActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        btnEnviar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/825423486012620863/1124346650941468672/Group_22_4.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_txtDescActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try {
            String chave = txtPix.getText();
            DAO dao = new DAO();
            ArrayList todasChaves = dao.todasChavesPix();
            if(todasChaves.contains(chave)){
                String textvalor = txtValor.getText();
                String textValorCerto = textvalor.replace(',', '.');
                double pix = Double.parseDouble(textValorCerto);
                double valor = pix;            
                int destinatario = dao.verificaCodPix(chave);
                String descricao = txtDesc.getText();
                double saldodestinatario = dao.verificaSaldo(destinatario);
                double saldofinaldest = saldodestinatario + valor;
                TelaDigiteSenha tds = new TelaDigiteSenha(logado,valor,3,destinatario,descricao,saldofinaldest,chave);
                tds.setVisible(true);
                int id = 1;
                if(confirmacao){
                    LocalDate dataAtual = LocalDate.now();
                    String data = dataAtual.toString();

                    try {
                        double novoSaldo = logado.getSaldo() - valor;
                        logado.setSaldo(novoSaldo);
                        ArrayList listaId = dao.todasTransferencias();
                        while(listaId.contains(id)){
                            id++;
                        }
                        dao.fazerPix(id,valor,data, logado,novoSaldo,destinatario,descricao,saldofinaldest,chave);
                        JOptionPane.showMessageDialog(null,"Você fez um depósito de: \n R$ " + valor);
                    } catch (Exception ex) {
                        Logger.getLogger(TelaDeposito.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
            else{
                int tipo = 13;
                TelaAvisos ta = new TelaAvisos(tipo);
                ta.setVisible(true);
            }
            this.confirmacao = false;            
        } catch (Exception ex) {
            Logger.getLogger(TelaTransferir.class.getName()).log(Level.SEVERE, null, ex);
            int tipo = 12;
            TelaAvisos ta = new TelaAvisos(tipo);
            ta.setVisible(true);
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseEntered
        btnEnviar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnEnviar2.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnEnviarMouseEntered

    private void btnEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseExited
        btnEnviar.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://github.com/Andrey-de-Freitas-Souza/html-css/blob/main/Imagens/btnEnviar.png?raw=true")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
    }//GEN-LAST:event_btnEnviarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtPix;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
